logging.level:
 org.springframework: ERROR
 org.springframework.web: INFO
 # logs the SQL statements
 org.hibernate.SQL: DEBUG 
 # Logs the JDBC parameters passed to a query
 org.hibernate.type: TRACE 

spring:
 application:
  name: Hello World Webapp
 main:
  show_banner: false
 output.ansi.enabled: ALWAYS

 datasource:
#  jndi-name: jdbc/customerdb
  url: jdbc:hsqldb:hsql://localhost/prod;shutdown=true;hsqldb.write_delay_millis=0
  username: sa
  password:
  driver-class-name: org.hsqldb.jdbcDriver

 jpa:
#  show-sql: true
  hibernate.ddl-auto: none

who: Quentin

server:
 port: 9010
 
#liquibase:
# changelog: classpath:/com/saltoconsulting/dojo/db/changelog/db.changelog-master.xml