logging.level:
 org.springframework: ERROR
 org.springframework.web: INFO

spring:
 application:
  name: Hello World Webapp
 main:
  show_banner: false
 output.ansi.enabled: ALWAYS

 datasource:
#  jndi-name: jdbc/customerdb
  url: jdbc:hsqldb:hsql://localhost/firstdb
  username: sa
  password:
  driver-class-name: org.hsqldb.jdbcDriver

 jpa:
  show-sql: true
  hibernate.ddl-auto: none

who: Quentin

server:
 port: 9000
 
#liquibase:
# changelog: classpath:/com/saltoconsulting/dojo/db/changelog/db.changelog-master.xml