# Config for ${project.artifactId}-${project.version}
who: __ENVIRONMENT__

logging.level:
 org.springframework: ERROR

spring:
 application:
  name: Hello World App
 main:
  show_banner: true

this.is.a.new.property: yeah

this.is.a.new.property.again: cool
this.is.a.new.property.again.again: cool
